# version: '3.12'

# services:
#   postgres:
#     image: postgres:16
#     environment:
#       POSTGRES_DB: testdb
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 1234
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   springboot:
#     image: jarfile  # Reference the prebuilt image
#     depends_on:
#       - postgres
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/testdb
#       SPRING_DATASOURCE_USERNAME: postgres
#       SPRING_DATASOURCE_PASSWORD: 1234
#     ports:
#       - "8080:8080"

# volumes:
#   postgres_data:


version: '3.12'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  springboot:
    image: jarfile
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/testdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8080:8080"

  frontend:
    image: svepro                    # ✅ Use prebuilt Svelte image
    depends_on:
      - springboot
    ports:
      - "3000:80"                    # 3000 on host → 80 inside container (Nginx)

volumes:
  postgres_data:
